language: c

env:
  global:
    - LUAROCKS=2.2.0
    - ROCKSPEC=lyaml-git-1.rockspec
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  # Put back the links for libyaml, which are missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;
  - sudo apt-get install help2man
  - bash .travis/setup_lua.sh

install:
  # Install extra rocks into $LUAROCKS_CONFIG rocks tree.
  - sudo luarocks install specl;

  # Make git rockspec
  - make rockspecs V=1
    || cat $ROCKSPEC

  - sudo luarocks make $ROCKSPEC LUA="$LUA"

script:
  - make check V=1

  # Run sanity checks on CI server, ignoring buggy automakes.
  - '{ _assign="=";
       grep local-checks-to-skip build-aux/sanity-cfg.mk >/dev/null && _assign="+=";
       printf "local-checks-to-skip %s
       sc_vulnerable_makefile_CVE-2012-3386\n" "$_assign";
     } >> build-aux/sanity-cfg.mk'
  - 'make syntax-check || :'

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
